apiVersion: apps/v1
kind: Deployment
metadata:
  name:consignment-service-deployment
  labels:
    app:consignment-service
  spec:
    replicas: 2
    selector:
      matchLabels:
        app:consignment-service
    template:
      metadata:
        labels:
          app:consignment-service
      spec:
        restartPolicy: Always #表明该容器一直运行，默认k8s的策略，在此容器退出后，会立即创建一个相同的容器 
        #表示要部署到哪个node上
        #nodeSelector: node1 
        containers:
        - name:consignment-service  
          image:consignment-service:v1
          # 定义环境变量
          evn:
          - DB_HOST:192.168.1.101:27017
            MICRO_SERVER_ADDRESS: :50051
            MICRO_REGISTRY: consul
          ports:
          - name:tcp
            containerPort: 50051
            protocol: TCP

	  