apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vessel-service
  labels:
    app: vessel-service
spec:
  replicas: 2
  serviceName: vessel-service
  selector:
    matchLabels:
      app: vessel-service
  template:
    metadata:
      labels:
        app: vessel-service
    spec:
      #表明该容器一直运行，默认k8s的策略，在此容器退出后，会立即创建一个相同的容器 
      restartPolicy: Always 
      #表示要部署到哪个node上
      #nodeSelector: node1 
      containers:
      - name: vessel-service  
        image: 192.168.1.101:5000/vessel-service:v1
        # 定义环境变量
        env:
        - name: DB_HOST
          value: 192.168.1.101:27017
        - name: ConsulRegistry
          value: 10.1.99.48:8500
        - name: MICRO_REGISTRY
          value: consul
        - name: PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MICRO_SERVER_ADDRESS
          value: $(PODIP):50052
        ports:
        - name: tcp
          containerPort: 50052
          protocol: TCP